### ISSUE TITLE
Zpětná vazba životopis

### ISSUE THREAD

**Issue by IxAriela** [8venom8/zivotopis02#1]
Ahoj, první mrknu na ten jednodušší, jednostránkový :)

Br je zalomení řádku a píše se na konci, na začátku není třeba :) Tedy žádný první řádek by mít br neměl, stejně tak by se nemělo používat více br pod sebou (to tam nemáš, ale stává se to).

Je dobré pojmenovávat třídy podle obsahu, někdy se tedy hodí jedna, dva, tři, v případě životopisu by možná bylo lepší třeba praxe, vzdelani apod. Toto je pro tebe, tak je mi to celkem jedno, ale v praxi málokdy člověk dělá projekt sám a je fajn i ostatním co nejvíce zjednodušit orientaci v kodu :)

Při psaní css se hodí mít nějaký systém i v tom, jak jdou prvky za sebou. Při větších projektech se v tom jinak ztratíš :) Nejčastěji se asi používá podle toho, jak to jde v html od vrchu dolů, ve tvém případě by bylo fajn mít za sebou nadpisy, pak taky u sebe třídy .jedna, .dva, ...

K opravě:

- [x] Ul type disc nepatří do html, tam můžeš dát class disc a pak v css list-style: disc; žádné css styly nepatří do html kodu (pokud to není nutné, jsou určité výjimky). I kvůli přehlednosti, za měsíc se k tomu zkusíš vrátit a budeš to 10 minut hledat, kde to změníš :) navíc v html je velmi těžké to přepsat přes css (html má přednost).
- [x] Prosím dodržuj postupnost nadpisů, za H1 patří H2, sémantika je taky důležitá :)
- [x] u .jedna, .tri, .pet ti chybí středník na konci
- [x] třída .nove_mesto_na_morave_ se v html nevyskytuje, zkus nemít v css žádnou třídu, která se nepoužívá. Navíc proč je tam to poslední _ (to asi ničemu nevadí, ale opět je to matoucí pro ostatní)?

**Comment by 8venom8** [comment]
Ahoj, moc děkuju za opravu :) Opravila jsem všechno. Přejmenovala jsem si i třídy podle obsahu a seřadila jsem prvky jak jdou za sebou, nadpisy k nadpisům. Mám teď <br> použito správně? Vyskytuje se mi tam docela často, nevím jestli to takto může být. A jak by se nepárové značky měly ideálně psát? Jen takto </br> nebo pouze takto <br> nebo je to jedno ?  Musím zapracovat na přehlednosti kódu, sama jsem teď byla ztracená a to jsem to neviděla jen chvíli. Děkuju :)

**Comment by 8venom8** [comment]
Ještě jednou: Mám teď `<br>` použito správně? Vyskytuje se mi tam docela často, nevím jestli to takto může být. A jak by se nepárové značky měly ideálně psát? Jen takto `<br>` nebo `</br>`   nebo je to jedno ?

**Comment by 8venom8** [comment]
Ahoj, moc děkuju za opravu :) Opravila jsem všechno. Přejmenovala jsem si i třídy podle obsahu a seřadila jsem prvky jak jdou za sebou, nadpisy k nadpisům. Mám teď `<br>` použito správně? Vyskytuje se mi tam docela často, nevím jestli to takto může být. A jak by se nepárové značky měly ideálně psát? Jen takto `<br>` nebo `</br>` nebo je to jedno ? Musím zapracovat na přehlednosti kódu, sama jsem teď byla ztracená a to jsem to neviděla jen chvíli. Děkuju :)

**Comment by IxAriela** [comment]
Super, teď máš i použití br správně :) že jich je hodně nevadí, je to odentrování. Je fakt, že většinou jich nebývá použito tolik, dává se to třeba do více odstavců. Nebo když je toho víc, jak to máš ty, tak se to dá i seznamem, akorát v css zrušíš odrážky. Ale takto to není špatně.

Nepárové značky se ve starších verzích html musely psát `</br>`, jinak to prohlížeče nepřečetly. V dnešní době už to není třeba, všechny prohlížeče už to zvládnou i bez lomítka, takže záleží na tvé preferenci :)

Až si to přečteš, tak to issue prosím uzavři.

**Comment by 8venom8** [comment]
Děkuju ti za kontrolu a za zprávu :) Issue tedy zavírám :)
